#!/bin/bash

if [ ! -e /usr/share/X11/xkb/symbols/sbs-no-mac-nodead ]; then
	echo "Creating layout sbs-no-mac-nodead.";
	sudo cp ./assets/no-mac.xkb /usr/share/X11/xkb/symbols/sbs-no-mac-nodead;
fi

#Set the layout
setxkbmap -layout sbs-no-mac-nodead -variant mac